site_name: CiviBanking
repo_url: https://github.com/systopia/CiviBanking
theme: material

pages:
- Description: CiviBanking.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
